import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: {
    default: "Learning Next.js",
    template: "%s | Learning Next.js",
    keywords: ['nextjs', 'react', 'javascript', 'tailwindcss', 'css', 'html', 'web development', 'frontend']
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#03122F] text-white min-h-screen flex flex-col`}
      >
      <NavBar></NavBar>
      <main className="flex-1">
        {children}
      </main>
        
        <footer className="text-center bg-[#413B61]">This is a footer</footer>
      </body>
    </html>
  );
}
